"""Pydantic API request and response schemas with rich documentation and examples."""

from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field
from backend.core.constants import FEATURE_COUNT, SCHEMA_VERSION


class PredictRequest(BaseModel):
    """
    Inference request for a single network flow sample.
    Accepts an ordered list of exactly 78 numeric values, or a key-value dictionary of 78 features.
    """
    features: Union[List[float], Dict[str, float]] = Field(
        ...,
        description=f"Exactly {FEATURE_COUNT} numeric feature values or canonical dictionary map.",
        json_schema_extra={
            "example": {
                "features": [0.0] * FEATURE_COUNT
            }
        }
    )


class SampleItem(BaseModel):
    """A single sample in a batch inference request."""
    features: Union[List[float], Dict[str, float]] = Field(
        ...,
        description=f"Exactly {FEATURE_COUNT} numeric feature values.",
    )


class BatchPredictRequest(BaseModel):
    """Batch inference request containing multiple network flow samples."""
    samples: List[SampleItem] = Field(
        ...,
        min_length=1,
        description="List of feature vectors to classify in batch.",
        json_schema_extra={
            "example": {
                "samples": [
                    {"features": [0.0] * FEATURE_COUNT},
                    {"features": [1.0] * FEATURE_COUNT},
                ]
            }
        }
    )


class ClassPrediction(BaseModel):
    """Predicted threat class details."""
    class_id: int = Field(..., description="Canonical class identifier (0: BENIGN, 1: DDOS, 2: RECON, 3: SLOW_HTTP, 4: DNS_TUNNEL, 5: C2_BEACON)")
    class_name: str = Field(..., description="Canonical threat class label name")
    subtypes: List[str] = Field(default_factory=list, description="Sub-threat taxonomy (e.g. TCP SYN Flood, UDP Flood for DDOS)")


class ModelInfo(BaseModel):
    """Model information descriptor."""
    provider: str = Field(..., description="Provider type: 'mock', 'local', or 'external'")
    model_version: str = Field(..., description="Model version string")
    schema_version: str = Field(default=SCHEMA_VERSION, description="Feature schema version (e.g., '78d-v1')")
    feature_count: int = Field(default=FEATURE_COUNT, description="Expected feature dimension count (78)")
    is_mock: bool = Field(..., description="Whether inference was generated by a development mock adapter")


class PredictResponse(BaseModel):
    """Prediction response for a single feature vector."""
    prediction: ClassPrediction = Field(..., description="Threat classification prediction")
    confidence: Optional[float] = Field(None, description="Prediction confidence score between 0.0 and 1.0")
    probabilities: Optional[Dict[str, float]] = Field(None, description="Class-wise probability distribution across canonical classes")
    model: ModelInfo = Field(..., description="Metadata of the model serving inference")
    latency_ms: float = Field(..., description="Inference processing latency in milliseconds")
    mode: Optional[str] = Field(None, description="Marked 'mock' if running in development mock mode")
    sample_index: Optional[int] = Field(None, description="Index of the sample if executed within a batch request")


class BatchPredictResponse(BaseModel):
    """Batch prediction response containing results for all submitted samples."""
    results: List[PredictResponse] = Field(..., description="List of predictions matching the order of input samples")
    total_samples: int = Field(..., description="Total count of evaluated samples")
    model: ModelInfo = Field(..., description="Model descriptor")
    latency_ms: float = Field(..., description="Total batch execution time in milliseconds")
    mode: Optional[str] = Field(None, description="Marked 'mock' if running in development mock mode")


class HealthResponse(BaseModel):
    """Liveness probe response indicating the backend service is running."""
    status: str = Field(default="ok", description="Liveness status")
    service: str = Field(default="unidetect-backend", description="Service name")
    model_loaded: bool = Field(..., description="Whether the ML model is loaded and ready")


class ReadinessResponse(BaseModel):
    """Readiness probe response indicating whether inference can be performed."""
    ready: bool = Field(..., description="True if backend is fully ready to perform inference")
    status: str = Field(..., description="'READY' or 'NOT_READY'")
    reason: Optional[str] = Field(None, description="Reason if not ready")
    provider: str = Field(..., description="Configured model provider")


class ModelStatusResponse(BaseModel):
    """Detailed status report of the active ML model."""
    loaded: bool = Field(..., description="Whether model is loaded")
    provider: str = Field(..., description="Configured provider (mock, local, external)")
    is_mock: bool = Field(..., description="Whether model is a mock")
    model_name: str = Field(..., description="Identifier name of the model")
    model_version: str = Field(..., description="Model version")
    schema_version: str = Field(..., description="Expected feature schema version")
    feature_count: int = Field(..., description="Expected feature dimension (78)")
    metadata: Dict[str, Any] = Field(..., description="Additional metadata without secrets")


class ErrorDetail(BaseModel):
    """Structured error payload details."""
    code: str = Field(..., description="Error machine-readable code (e.g. INVALID_FEATURE_VECTOR, MODEL_NOT_LOADED)")
    message: str = Field(..., description="User-friendly explanation of the error")
    details: Optional[Dict[str, Any]] = Field(default=None, description="Additional context or validation details")


class ErrorResponse(BaseModel):
    """Standardized error response body."""
    error: ErrorDetail
